<?php

namespace ProcessWire;

class ImageFromPageHookHelper extends WireData implements Module
{
    /**
     * Return an array of module information
     *
     * @return array
     */
    public static function getModuleInfo()
    {
        return array(
            'title' => 'Hook Helper Module for FieldtypeImageFromPage',
            'version' => 004,
            'summary' => __('Adds hooks to Pagefiles to cleanup stored data from FieldtypeImageFromPage.'),
            'author' => 'Gerhard Sitzmann',
            'href' => '',
            'autoload' => true,
            'requires' => array(
                'FieldtypeImageFromPage',
                'PHP>=7.1.0',
                'ProcessWire>=3.0.120'
            )
        );
    }

    public function init()
    { 

        $this->addHookBefore('Pagefiles::delete', $this, 'cleanupFieldtypeImageFromPageData');
    }
    
    /**
     * Executes before an image gets deleted that lives on a page which holds images for FieldtypeImageFromPage
     * If references to that image are found on other pages, deletion is prevented and error messages are shown.
     *
     * @param Hookevent $event
     * @return void
     */
    public function cleanupFieldtypeImageFromPageData(Hookevent $event)
    {
        $thisFieldname = $event->object->field;
        // get fields of type imagefrompage that have this imagesfield assigned
        $fields = $this->getRelevantFields($thisFieldname);
        $imagePageIds = $this->getImagePageIds($fields);
        $deleted = $event->arguments(0);
        $pageid = $deleted->page->id;
        if(!in_array($pageid, $imagePageIds)) return;
        $filename = $deleted->basename;
        $fieldnames = array_map(function($f) {
            return $f->name;
        }, $fields);
        $pagelist = '';
        foreach($fieldnames as $name) {
            $pages = $this->wire('pages')->find("{$name}.filename={$filename}, {$name}.pageid={$pageid}, include=all");
            if($pages->count) {
                $label = $pages->first()->getField($name)->label;
                $pagelist .= "References to remove in field: <em>{$label}</em><br>";
                $pagelist .= '<ul>';
                foreach($pages as $p) {
                    $pagelist .= "<li>Page title: <em>{$p->title}</em>, Page path: <em>{$p->path}</em> &nbsp;<a href='{$p->editUrl}&field={$name}' title='Edit page in new tab' target='_blank'><strong>Edit page</strong></a></li>";
                }
                $pagelist .= '</ul>';
            } 
        }
        if($pagelist) {
            $message = sprintf(
                $this->_('You cannot delete image %s as it is being used on other pages. Remove the references on those pages.')
                , "<em>{$filename}</em>"
            ) . '<br>';
            $message .= "{$pagelist}<br>";
            $message .= 'After all references are removed, you may delete this image';
            $event->object->error($message, Notice::allowMarkup);
            $event->replace = true; // prevents deletion
        }
    }

    /**
     * Collects IDs of all pages and their children that  hold images for fields of type FieldtypeImageFromPage
     *
     * @param array $fields all relevant fields of type FieldtypeImageFromPage
     * @return array array of page ids
     */
    public function getImagePageIds($fields) {
        $ids = array();
        foreach($fields as $f) {
            $ids[] = $f->imagespage;
        }
        $pages = $this->wire('pages')->find($ids, array('include' => 'hidden'));
        foreach($fields as $field) {
            if($field->includechildren) {
                foreach($pages as $p) {
                    $pages->add($p->children('include=all'));
                }
            }
        }

        return $pages->explode('id');
    }

    /**
     * get names of imagefrompage fields that have an imagesfield with name $imagesfield assigned
     *
     * @param string $imagesfield name of the imagesfield
     * @return array array of fields of type FieldtypeImageFromPage
     */
    public function getRelevantFields($imagesfield) {
        $fields = array();
        foreach($this->wire('fields') as $f) {
            if($f->type instanceof FieldtypeImageFromPage && $f->imagesfield == $imagesfield) $fields[] = $f;
        }
        return $fields;
    }
}
