<?php

namespace ProcessWire;
/**
 * Inputfield 'Image Picker' provides a means for selecting images from a predefined page and it's children.
 * Per field you can set a page to list from.
 *
 * ©2019 Gerhard Sitzmann
 *
 * ProcessWire 3.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class InputfieldImageFromPage extends Inputfield implements Module
{

    /**
     * holds all pages with images
     *
     * @var Pages
     */
    protected $imagePages;

    /**
     * Return an array of module information
     *
     * @return array
     */
    public static function getModuleInfo()
    {
        return array(
            'title' => 'Select Image From Page',
            'version' => 005,
            'summary' => __('Inputfield to select a single image from images on a predefined page and it\'s children.'),
            'author' => 'Gerhard Sitzmann',
            'href' => '',
            'requires' => array(
                'FieldtypeImageFromPage',
                'PHP>=7.1.0',
                'ProcessWire>=3.0.120'
            )
        );
    }

    /**
     * populates properties
     *
     * @return void
     */
    public function populateValues()
    {
        $this->imagePages = $this->getImagePages();
    }

    /**
     * populates config JS
     *
     * @return void
     */
    public function populateConfigJs()
    {
        $input = $this->wire('input');
        if ($this->process == 'ProcessPageEdit') { // we are on a page edit screen
            $editPageUrl = $this->wire('pages')->get($input->id)->editUrl . "&InputfieldImageFromPage=1";
        } else { // other page 
            $editPageUrl = $this->page->url . "?InputfieldImageFromPage=1";
        }
        $this->wire('config')->js($this->className, array(
            'url' => $editPageUrl
        ));
    }

    /**
     * Set an attribute to this Inputfield
     *
     * In this case, we just capture the 'value' attribute and make sure it's something valid
     * 
     * @param string $key
     * @param mixed $value
     * @return $this
     * @throws WireException
     *
     */
    public function setAttribute($key, $value)
    {
        if ($key == 'value' && empty($value)) {
            // $value = new ImageFromPage;
            $value = $this->toJson();
            // bd($value, 'setAttribute empty');
            // throw new WireException("This input only accepts a ImageFromPage for it's value");
        } elseif ($key == 'value' && $value) {
            // $value = $this->toJson($value->pageid, $value->filename);
        }

        return parent::setAttribute($key, $value);
    }

    public function isEmpty()
    {
        return (!$this->value);
    }

    public function toJson($pageid = 0, $filename = '') {
        return json_encode(array('pageid' => $pageid, 'filename' => $filename));
    }


    /**
     * Return the completed output of Inputfield select file
     *
     * @return string
     *
     */
    public function ___render()
    {
        // bd($this->attr('value'), 'value');
        $this->populateValues();
        $this->populateConfigJs();
        $input = $this->wire('input');

        if ($input->InputfieldImageFromPage && $input->pageid) {
            echo $this->getThumbnailsForPage($input->pageid);
            exit;
        }

        // $id = $this->attr('id');
        $name = $this->attr('name');
        $value = json_decode($this->attr('value'));
        if ($value->pageid === -1) {
            $message = $this->_("The referenced image was deleted. Choose a new image");
            $this->page->error($this->_("The referenced image was deleted. Choose a new image"));
            $this->error($message);
        }
        $out = $this->renderSelectedImage($value);
        $out .= $this->renderInputs($name, $value);
        $out .= $this->renderThumbnails();

        return $out;
    }

    public function renderSelectedImage($value)
    {
        $previewWidth = ($this->previewWidth) ? $this->previewWidth : 200;
        $blankSrc = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mN89x8AAuEB74Y0o2cAAAAASUVORK5CYII=';
        if ($value && $value->filename) {
            $image = $this->wire('pages')->get($value->pageid)->get($this->imagesfield)->getFile($value->filename);
        }
        $url = (isset($image)) ? $image->width($previewWidth)->url : $blankSrc;
        $info = (isset($image)) ? $this->renderTooltip($image) : '';
        $out = "<div class='uk-panel uk-panel-box uk-margin-bottom'>
        <span class='fa fa-trash' uk-tooltip='title: Remove Image'></span>
        <img src='{$url}' style='width: {$previewWidth}px; max-width: {$previewWidth}px' data-src='{$blankSrc}'>
        <div class='uk-thumbnail-caption' style='max-width: {$previewWidth}px'>{$info}</div>";
        $out .= "</div>";

        return $out;
    }


    public function renderInputs($name, $value)
    {
        $jsonValue = '{"pageid": ' . $value->pageid . ', "filename": "' . $value->filename . '"}';
        return "<div>
        <input type='hidden' class='imagefrompage_value' name='{$name}' id='{$name}' value='{$jsonValue}' \>
        </div>";
    }

    public function renderThumbnails()
    {
        $wrapper = new InputfieldWrapper;
        foreach ($this->imagePages as $p) {
            $wrapper->add($this->renderThumbnailsForPage($p));
        }

        return $wrapper->render();
    }

    /**
     * renders thumbnails for an image page inside an InputfieldMarkup
     *
     * @param Page $page
     * @return InputfieldMarkup inputfield markup instance
     */
    public function renderThumbnailsForPage($page)
    {
        $button = "<a href='{$page->editUrl}&field={$this->imagesfield}&from=imagefrompage' class='imagefrompage_editimages pw-modal' title='" . $this->_('Upload Images') . "' uk-tooltip data-buttons='button#submit_save' data-autoclose><span class='fa fa-upload'></span></a>";


        $markup = '<ul class="uk-thumbnav uk-grid-width-1-6" data-pageid="' . $page->id . '">';
        if (!$this->useajax) $markup .= $this->getThumbnailsForPage($page->id);
        $markup .= '</ul>';
        $markupField = new InputfieldMarkup; // $this->wire('modules')->get('InputfieldMarkup');
        $markupField->class('imagefrompage_thumbholder');
        // $markupField->attr('data-pageid', $page->id); // does not work
        $markupField->label = $this->_('Choose an image from') . ' ' . $page->title;
        $markupField->entityEncodeLabel = false;
        $markupField->markupText = $button . $markup;
        $markupField->collapsed(1); // collapse when Icon already chosen

        return $markupField;
    }

    /**
     * renders thumbnails markup for an image page
     *
     * @param int $page
     * @return string thumbnail markup for page images
     */
    public function getThumbnailsForPage($pageid)
    {
        $page = $this->wire('pages')->get($pageid);
        $images = $page->get($this->imagesfield);
        if (!$images->count) {
            $markup = '<b>' . $this->_('There are no images. Upload images to page') . ' ' . $page->title . '</b>';
        } else {
            $thumbWidth = ($this->thumbWidth) ? $this->thumbWidth : 100;
            // $markup = '<ul class="uk-thumbnav uk-grid-width-1-6">';
            $markup = '';
            foreach ($images as $img) {
                $tooltip = $this->renderTooltip($img);
                $markup .= "<li class='uk-thumbnail uk-thumbnail-mini'>
                <img style='max-width: {$thumbWidth}px; width: {$thumbWidth}px' data-pageid='{$page->id}' data-filename='{$img->basename}' src='{$img->width($thumbWidth)->url}' alt='{$img->basename}'  uk-tooltip='{$tooltip}'>
                </li>";
            }
            // $markup .= '</ul>';
        }

        return $markup;
    }

    public function renderTooltip(Pageimage $img)
    {
        $out = $img->basename;
        if ($img->description) $out .= '<br>' . $img->description;
        $out .= '<br>' . $img->filesizeStr;
        if (strtolower($img->ext) !== 'svg') $out .= '<br>' . "{$img->width} x {$img->height} px";

        return $out;
    }

    /**
     * gets all pages that serve image thumbnails to the inputfield
     *
     * @return Pages
     */
    public function getImagePages()
    {
        $pages = $this->wire('pages')->find($this->imagespage, array('include' => 'hidden'));
        if ($this->includechildren) {
            foreach ($pages->first()->children('include=hidden') as $child) {
                if ($child->hasField($this->imagesfield)) $pages->add($child);
            }
        }
        return $pages;
    }

    /**
     * Process the input after a form submission
     * 
     * @param WireInputData $input
     * @return $this
     *
     */
    public function ___processInput(WireInputData $input)
    {
        $name = $this->attr('name');
        $value = $this->attr('value');
        $valueObj = json_decode($value);
        $newValue = json_decode($input[$name]);
        if (!isset($newValue->filename) && !isset($newValue->pageid)) return $this;
       
        $filename = $newValue->filename;
        $pageid = $newValue->pageid;
        if($valueObj->filename == $filename && $valueObj->pageid == $pageid) return $this;

        $this->attr('value', json_encode($newValue));

        $page = ($this->hasPage) ? $this->hasPage : $this->page;
        $page->set($name, $this->attr('value'));

        return $this;
    }
}
